// src/features/daily_review/i18n/en.ts

export const enTexts = {
  // --- コメント（複数行） ---
  'daily-review-comment': [
    'The following summary was generated by an LLM based on today’s activities.',
    'Please check incorrect lines and add review comments if necessary.',
    'These review comments will be used in the subsequent KPT analysis.',
  ],

  'kpt-action-comment': [
    'Review comments will be reflected in the KPT analysis.',
    'Please revise or add notes, then run the KPT analysis.',
  ],

  'daily-review-unregistered-guide': [
    '※ Some unregistered tags were detected.',
    '-> Please use the command "**Register and Merge Tags into Alias Dictionary**" to normalize them.',
  ],

} as const;
